"""empty message

Revision ID: 596d6dd5078a
Revises: f89563780ed2
Create Date: 2022-11-16 19:39:15.843205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596d6dd5078a'
down_revision = 'f89563780ed2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
